# simple make file, will need more documentation
server_array_queue_fork: server_array_queue_fork.c array_queue_fork.c
	gcc -pthread -o server_array_queue_fork server_array_queue_fork.c array_queue_fork.c -lrt
